server:
  port: 8080

spring:
  application:
    name: discodeit

  boot:
    admin:
      client:
        url: http://localhost:9090

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com.sprint.mission.discodeit: debug
