server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/${POSTGRES_DB_DEV}
    username: ${POSTGRES_USER_DEV}
    password: ${POSTGRES_PASSWORD_DEV}
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        ddl-auto:

logging:
  level:
    com.sprint.mission.discodeit: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: trace
    org.springframework.web: debug

management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true