spring:
  application:
    name: discodeit

  servlet:
    multipart:
      max-file-size: 10MB       # 파일 1개 최대
      max-request-size: 20MB    # 요청 전체(여러 파일 합) 최대

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: discodeit_schema

logging:
  level:
    root: info

discodeit:
  storage:
    type: local
    local:
      root-path: C:\myWs\uploadedFiles
