spring:
  application:
    name: discodeit

  servlet:
    multipart:
      max-file-size: 10MB       # 파일 1개 최대
      max-request-size: 20MB    # 요청 전체(여러 파일 합) 최대
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit?currentSchema=discodeit_schema
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: discodeit_schema

logging:
  level:
    root: info

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        # 외부로 노출할 엔드포인트 지정
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: when-authorized
      show-components: always

# 애플리케이션 및 주요 설정 정보
info:
  app:
    name: Discodeit
    version: 1.7.0
    java: 17
    spring-boot: 3.5.8

  # 주요 설정 정보
  config:
    datasource:
      url: ${spring.datasource.url:unknown}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto:unknown}
    storage:
      type: ${discodeit.storage.type:unknown}
      path: ${discodeit.storage.local.root-path:unknown}
    multipart:
      max-file-size: ${spring.servlet.multipart.max-file-size:unknown}
      max-request-size: ${spring.servlet.multipart.max-request-size:unknown}

discodeit:
  storage:
    type: ${STORAGE_TYPE:local} # s3로 설정 시 S3 모드 활성화
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION:unknown}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}
    local:
      root-path: C:\myWs\uploadedFiles
