spring:
  application:
    name: discodeit

  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true

  aop:
    proxy-target-class: true

  kafka:
    bootstrap-servers: localhost:9092

  data:
    redis:
      host: localhost

logging:
  level:
    com.sprint.mission.discodeit: debug
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: trace

